"""
Per-user investigator workspace: saved projects, investigations, audit cases.

All recommendation/priority data shown here is generated by the existing
audit_intel module from recorded project data — nothing is user-editable
except workflow status and notes, so nothing can be fabricated.
"""

import json
from datetime import datetime, timedelta, timezone
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from jose import JWTError, jwt
from pydantic import BaseModel, EmailStr, Field, field_validator
from sqlalchemy.orm import Session

import auth
import models
import audit_intel
from auth import get_db  # same session dependency auth.py declares

try:
    from email_validator import validate_email  # optional hardening
except Exception:  # pragma: no cover
    validate_email = None


def _email_ok(email: str) -> bool:
    """Syntax-only validation (no DNS lookup, so it works offline)."""
    if validate_email is None:
        return "@" in email and "." in email.split("@", 1)[1]
    try:
        validate_email(email, check_deliverability=False)
        return True
    except Exception:
        return False

router = APIRouter(prefix="/auth", tags=["Authentication"])
_bearer = HTTPBearer(auto_error=False)

USER_STATUSES = ("Open", "Under Review", "Resolved")

# ═══════════════ Schemas ═══════════════

class SignupRequest(BaseModel):
    name: str = Field(min_length=2, max_length=120)
    email: EmailStr
    password: str = Field(min_length=8, max_length=128)
    # Role is self-service capped at analyst; field/audit/admin roles are
    # provisioned by an admin. 'public' is the unauthenticated tier and not a
    # signup choice.
    role: str = "citizen"

    @field_validator("role")
    @classmethod
    def _role_cap(cls, v: str) -> str:
        if v not in ("citizen", "analyst", "auditor"):
            raise ValueError("role must be 'citizen', 'analyst' or 'auditor' — field and admin roles are provisioned by an admin")
        return v


class LoginRequest(BaseModel):
    email: EmailStr
    password: str


class ForgotRequest(BaseModel):
    email: EmailStr


class ResetRequest(BaseModel):
    token: str
    new_password: str = Field(min_length=8, max_length=128)


class UserOut(BaseModel):
    id: int
    name: str
    email: str
    role: str
    is_active: bool
    created_at: str
    assigned_district: Optional[str] = None
    assigned_state: Optional[str] = None

    class Config:
        from_attributes = True


class MeOut(BaseModel):
    """Signed-in profile + effective server-side capabilities so the UI can
    render role-aware navigation without ever being the enforcement point."""

    id: int
    name: str
    email: str
    role: str
    is_active: bool
    created_at: str
    assigned_district: Optional[str] = None
    assigned_state: Optional[str] = None
    capabilities: list[str] = []

    class Config:
        from_attributes = True


class UserAdminUpdate(BaseModel):
    role: Optional[str] = None
    is_active: Optional[bool] = None
    assigned_district: Optional[str] = None
    assigned_state: Optional[str] = None

    @field_validator("role")
    @classmethod
    def _valid_role(cls, v):
        if v is not None and v not in auth.ROLES:
            raise ValueError(f"role must be one of {auth.ROLES}")
        return v


class UserCreateRequest(BaseModel):
    """Admin provisioning — any role, with optional district assignment."""

    name: str = Field(min_length=2, max_length=120)
    email: EmailStr
    password: str = Field(min_length=8, max_length=128)
    role: str = "analyst"
    assigned_district: Optional[str] = None
    assigned_state: Optional[str] = None

    @field_validator("role")
    @classmethod
    def _valid_role(cls, v):
        if v not in auth.ROLES or v == "public":
            raise ValueError(f"role must be one of {auth.ROLES[1:]}")
        return v


class WorkspaceStatusUpdate(BaseModel):
    status: str


class CaseStatusUpdate(BaseModel):
    status: str


# ═══════════════ Helpers ═══════════════

def _now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S")


def _issue_token(user: models.User) -> str:
    return auth.create_access_token(user.id, user.role)


def _user_payload(user: models.User, token: str) -> dict:
    """Login/signup response. Includes effective capabilities so the UI can
    render role-aware navigation immediately without a follow-up /me call."""
    return {
        "user": UserOut.model_validate(user).model_dump()
        | {"capabilities": sorted(auth.user_capabilities(user))},
        "token": token,
        "token_type": "bearer",
    }


def _project_or_404(db: Session, project_id: int) -> models.Project:
    project = db.query(models.Project).filter(models.Project.id == project_id).first()
    if not project:
        raise HTTPException(status_code=404, detail=f"Project {project_id} not found")
    return project


def _owned_investigation(db: Session, user: models.User, project_id: int) -> models.UserInvestigation:
    inv = (
        db.query(models.UserInvestigation)
        .filter(models.UserInvestigation.user_id == user.id, models.UserInvestigation.project_id == project_id)
        .first()
    )
    if not inv:
        raise HTTPException(status_code=404, detail="No investigation found for this project")
    return inv


def _sync_user_investigation_record(db: Session, user: models.User, project: models.Project) -> models.UserInvestigation:
    """
    Create/update the per-user investigation record, deriving priority and
    recommendations from the real risk data via the existing audit_intel
    engine. Also ensures the shared evidence-checklist workspace exists so
    the drawer keeps working as before.
    """
    # Shared workspace (evidence checklist) — same behaviour as before.
    audit_intel.start_investigation(db, project)

    existing = (
        db.query(models.UserInvestigation)
        .filter(models.UserInvestigation.user_id == user.id, models.UserInvestigation.project_id == project.id)
        .first()
    )
    risk_row = db.query(models.RiskScore).filter(models.RiskScore.project_id == project.id).first()
    risk_score = risk_row.risk_score if risk_row else 0
    _rec_row = (
        db.query(models.ProjectRecInfo)
        .filter(models.ProjectRecInfo.project_id == project.id)
        .first()
    )
    _linked_exp = float(_rec_row.linked_expenditure or 0.0) if _rec_row is not None else 0.0
    tier = audit_intel.priority_breakdown(
        project, risk_score, risk_level=(risk_row.risk_level if risk_row else None),
        linked_expenditure=_linked_exp,
    )

    # Recommendations come straight from the recorded risk reasons.
    reasons = [r.strip() for r in (risk_row.reasons or "").split(",") if r.strip()] if risk_row else []

    now = _now_iso()
    if existing:
        existing.risk_score_at_start = risk_score
        existing.updated_at = now
        inv = existing
    else:
        inv = models.UserInvestigation(
            user_id=user.id,
            project_id=project.id,
            status="Open",
            priority_tier=tier["tier"],
            priority_label=tier["tier_label"],
            risk_score_at_start=risk_score,
            recommendations=None,
            created_at=now,
            updated_at=now,
        )
        db.add(inv)

    inv.priority_tier = tier["tier"]
    inv.priority_label = tier["tier_label"]
    inv.recommendations = json.dumps(reasons[:6]) if reasons else None
    db.commit()
    db.refresh(inv)
    return inv


# ═══════════════ Authentication endpoints ═══════════════

@router.post("/signup", status_code=201)
def signup(payload: SignupRequest, db: Session = Depends(get_db)):
    email = payload.email.lower().strip()
    if not _email_ok(email):
        raise HTTPException(status_code=400, detail="Invalid email address")
    if db.query(models.User).filter(models.User.email == email).first():
        raise HTTPException(status_code=409, detail="An account with this email already exists")

    user_count = db.query(models.User).count()
    # First registered account becomes admin (bootstrap).
    role = "admin" if user_count == 0 else payload.role

    user = models.User(
        name=payload.name.strip(),
        email=email,
        password_hash=auth.hash_password(payload.password),
        role=role,
        is_active=True,
        created_at=_now_iso(),
    )
    db.add(user)
    db.commit()
    db.refresh(user)
    return _user_payload(user, _issue_token(user))


@router.post("/login")
def login(payload: LoginRequest, db: Session = Depends(get_db)):
    email = payload.email.lower().strip()
    user = db.query(models.User).filter(models.User.email == email).first()
    # Uniform error: never reveal whether the email exists.
    if not user or not auth.verify_password(payload.password, user.password_hash):
        raise HTTPException(status_code=401, detail="Invalid email or password")
    if not user.is_active:
        raise HTTPException(status_code=403, detail="This account has been deactivated")
    return _user_payload(user, _issue_token(user))


@router.post("/forgot-password")
def forgot_password(payload: ForgotRequest, db: Session = Depends(get_db)):
    """
    Always returns 200 with the same message, whether or not the email exists
    (prevents account enumeration). Since there is no mail server in this
    deployment, the single-use token is returned for the requester to use —
    this is documented behaviour, not a fabricated email flow.
    """
    user = db.query(models.User).filter(models.User.email == payload.email.lower().strip()).first()
    message = "If an account exists for this email, a reset token has been generated."
    reset_token = None
    if user and user.is_active:
        token = auth.create_reset_token()
        expires = (datetime.now(timezone.utc) + timedelta(minutes=auth.RESET_TOKEN_EXPIRE_MINUTES)).strftime("%Y-%m-%dT%H:%M:%S")
        db.add(models.PasswordReset(
            user_id=user.id,
            token=token,
            expires_at=expires,
            used=False,
            created_at=_now_iso(),
        ))
        db.commit()
        reset_token = token
    return {"message": message, "reset_token": reset_token, "note": "Token is valid for 30 minutes and can be used once."}


@router.post("/reset-password")
def reset_password(payload: ResetRequest, db: Session = Depends(get_db)):
    row = (
        db.query(models.PasswordReset)
        .filter(models.PasswordReset.token == payload.token, models.PasswordReset.used.is_(False))
        .first()
    )
    if not row:
        raise HTTPException(status_code=400, detail="Invalid or already-used reset token")
    if row.expires_at < _now_iso():
        raise HTTPException(status_code=400, detail="Reset token has expired")
    user = db.query(models.User).filter(models.User.id == row.user_id).first()
    if not user:
        raise HTTPException(status_code=400, detail="Account no longer exists")
    user.password_hash = auth.hash_password(payload.new_password)
    row.used = True
    db.commit()
    return {"message": "Password updated. You can now sign in with the new password."}


@router.get("/me", response_model=MeOut)
def me(current: models.User = Depends(auth.require_role("public"))):
    """Profile of the signed-in user incl. effective capabilities."""
    out = MeOut.model_validate(current).model_dump()
    out["capabilities"] = sorted(auth.user_capabilities(current))
    return out


# ═══════════════ User management (admin only) ═══════════════

@router.get("/users", dependencies=[Depends(auth.require_role("admin"))])
def list_users(db: Session = Depends(get_db)):
    users = db.query(models.User).order_by(models.User.id).all()
    return {"users": [UserOut.model_validate(u).model_dump() for u in users], "total": len(users)}


@router.post("/users", status_code=201, dependencies=[Depends(auth.require_role("admin"))])
def create_user(payload: UserCreateRequest, db: Session = Depends(get_db)):
    """Admin provisions an account with any role (e.g. Field Verifiers or
    District Authorities), optionally assigned to a district/state."""
    email = payload.email.lower().strip()
    if not _email_ok(email):
        raise HTTPException(status_code=400, detail="Invalid email address")
    if db.query(models.User).filter(models.User.email == email).first():
        raise HTTPException(status_code=409, detail="An account with this email already exists")
    user = models.User(
        name=payload.name.strip(),
        email=email,
        password_hash=auth.hash_password(payload.password),
        role=payload.role,
        is_active=True,
        created_at=_now_iso(),
        assigned_district=(payload.assigned_district.strip() if payload.assigned_district else None),
        assigned_state=(payload.assigned_state.strip() if payload.assigned_state else None),
    )
    db.add(user)
    db.commit()
    db.refresh(user)
    return UserOut.model_validate(user).model_dump()


@router.patch("/users/{user_id}", dependencies=[Depends(auth.require_role("admin"))])
def update_user(user_id: int, payload: UserAdminUpdate, db: Session = Depends(get_db), admin: models.User = Depends(auth.require_role("admin"))):
    user = db.query(models.User).filter(models.User.id == user_id).first()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    if payload.role is not None:
        user.role = payload.role
    if payload.is_active is not None:
        if user.id == admin.id and payload.is_active is False:
            raise HTTPException(status_code=400, detail="You cannot deactivate your own account")
        user.is_active = payload.is_active
    if payload.assigned_district is not None:
        user.assigned_district = payload.assigned_district.strip() or None
    if payload.assigned_state is not None:
        user.assigned_state = payload.assigned_state.strip() or None
    db.commit()
    return UserOut.model_validate(user).model_dump()


# ═══════════════ Saved projects (analyst+) ═══════════════

@router.get("/me/saved-projects")
def list_saved_projects(
    current: models.User = Depends(auth.require_role("analyst")),
    db: Session = Depends(get_db),
):
    """Saved projects for the signed-in user, enriched with real risk data."""
    rows = (
        db.query(models.SavedProject, models.Project, models.RiskScore)
        .join(models.Project, models.Project.id == models.SavedProject.project_id)
        .outerjoin(models.RiskScore, models.RiskScore.project_id == models.SavedProject.project_id)
        .filter(models.SavedProject.user_id == current.id)
        .order_by(models.SavedProject.saved_at.desc())
        .all()
    )
    items = []
    for saved, project, risk in rows:
        items.append({
            "saved_at": saved.saved_at,
            "project_id": project.id,
            "project_name": project.project_name,
            "state": project.state,
            "constituency": project.constituency,
            "status": project.status,
            "sanctioned_amount": project.sanctioned_amount,
            "expenditure": project.expenditure,
            "risk_score": (risk.risk_score if risk else None),
            "risk_level": (risk.risk_level if risk else None),
            "ml_anomaly": (bool(risk.ml_anomaly) if risk else False),
        })
    return {"items": items, "total": len(items)}


@router.post("/me/saved-projects/{project_id}", status_code=201)
def save_project(
    project_id: int,
    current: models.User = Depends(auth.require_role("analyst")),
    db: Session = Depends(get_db),
):
    _project_or_404(db, project_id)
    existing = (
        db.query(models.SavedProject)
        .filter(models.SavedProject.user_id == current.id, models.SavedProject.project_id == project_id)
        .first()
    )
    if existing:
        return {"saved": True, "already_saved": True, "saved_at": existing.saved_at}
    row = models.SavedProject(user_id=current.id, project_id=project_id, saved_at=_now_iso())
    db.add(row)
    db.commit()
    return {"saved": True, "already_saved": False, "saved_at": row.saved_at}


@router.delete("/me/saved-projects/{project_id}", status_code=200)
def remove_saved_project(
    project_id: int,
    current: models.User = Depends(auth.require_role("analyst")),
    db: Session = Depends(get_db),
):
    deleted = (
        db.query(models.SavedProject)
        .filter(models.SavedProject.user_id == current.id, models.SavedProject.project_id == project_id)
        .delete()
    )
    db.commit()
    return {"removed": bool(deleted)}


# ═══════════════ User investigations (analyst+) ═══════════════

@router.get("/me/investigations")
def list_my_investigations(
    current: models.User = Depends(auth.require_role("analyst")),
    db: Session = Depends(get_db),
):
    """Investigation history for the signed-in user."""
    rows = (
        db.query(models.UserInvestigation, models.Project)
        .join(models.Project, models.Project.id == models.UserInvestigation.project_id)
        .filter(models.UserInvestigation.user_id == current.id)
        .order_by(models.UserInvestigation.updated_at.desc())
        .all()
    )
    items = []
    for inv, project in rows:
        recommendations = []
        if inv.recommendations:
            try:
                recommendations = json.loads(inv.recommendations)
            except Exception:
                recommendations = []
        items.append({
            "investigation_id": inv.id,
            "project_id": project.id,
            "project_name": project.project_name,
            "state": project.state,
            "status": project.status,
            "investigation_status": inv.status,
            "risk_score_at_start": inv.risk_score_at_start,
            "priority_tier": inv.priority_tier,
            "priority_label": inv.priority_label,
            "recommendations": recommendations,
            "created_at": inv.created_at,
            "updated_at": inv.updated_at,
        })
    return {"items": items, "total": len(items)}


@router.post("/me/investigations/{project_id}", status_code=201)
def create_my_investigation(
    project_id: int,
    current: models.User = Depends(auth.require_role("analyst")),
    db: Session = Depends(get_db),
):
    """Start an investigation for a project. Creates the shared evidence
    checklist workspace (unchanged behaviour) plus the per-user record."""
    project = _project_or_404(db, project_id)
    inv = _sync_user_investigation_record(db, current, project)
    return {
        "investigation_id": inv.id,
        "project_id": project.id,
        "investigation_status": inv.status,
        "priority_tier": inv.priority_tier,
        "priority_label": inv.priority_label,
        "risk_score_at_start": inv.risk_score_at_start,
        "created_at": inv.created_at,
    }


@router.patch("/me/investigations/{project_id}")
def update_my_investigation(
    project_id: int,
    payload: WorkspaceStatusUpdate,
    current: models.User = Depends(auth.require_role("analyst")),
    db: Session = Depends(get_db),
):
    if payload.status not in USER_STATUSES:
        raise HTTPException(status_code=400, detail=f"status must be one of {USER_STATUSES}")
    inv = _owned_investigation(db, current, project_id)
    inv.status = payload.status
    inv.updated_at = _now_iso()
    db.commit()
    return {"investigation_id": inv.id, "project_id": inv.project_id, "investigation_status": inv.status, "updated_at": inv.updated_at}


# ═══════════════ Audit cases (auditor+) ═══════════════

@router.get("/me/audit-cases")
def list_my_cases(
    current: models.User = Depends(auth.require_role("auditor")),
    db: Session = Depends(get_db),
):
    rows = (
        db.query(models.AuditCase, models.Project)
        .join(models.Project, models.Project.id == models.AuditCase.project_id)
        .filter(models.AuditCase.user_id == current.id)
        .order_by(models.AuditCase.created_at.desc())
        .all()
    )
    # Linked per-user investigation status, if any
    inv_map = {
        i.project_id: i.status
        for i in db.query(models.UserInvestigation)
        .filter(models.UserInvestigation.user_id == current.id)
        .all()
    }
    items = []
    for case, project in rows:
        items.append({
            "case_row_id": case.id,
            "case_id": case.case_id,
            "project_id": project.id,
            "project_name": project.project_name,
            "state": project.state,
            "constituency": project.constituency,
            "risk_score": case.risk_score,
            "risk_level": case.risk_level,
            "priority_tier": case.priority_tier,
            "priority_label": case.priority_label,
            "case_status": case.status,
            "investigation_status": inv_map.get(project.id),
            "created_at": case.created_at,
        })
    return {"items": items, "total": len(items)}


@router.post("/me/audit-cases/{project_id}", status_code=201)
def save_audit_case(
    project_id: int,
    current: models.User = Depends(auth.require_role("auditor")),
    db: Session = Depends(get_db),
):
    """Save the generated audit case for a project to the user's account.
    The case content is always regenerated from live data when opened, so
    nothing stored here can go stale or be fabricated."""
    project = _project_or_404(db, project_id)
    generated = audit_intel.build_audit_case(project, db)
    existing = (
        db.query(models.AuditCase)
        .filter(models.AuditCase.user_id == current.id, models.AuditCase.project_id == project_id)
        .first()
    )
    now = _now_iso()
    if existing:
        existing.case_id = generated["case_id"]
        existing.priority_tier = generated["priority"]["tier"]
        existing.priority_label = generated["priority"]["tier_label"]
        existing.risk_score = generated["risk"]["risk_score"]
        existing.risk_level = generated["risk"]["risk_level"]
        existing.created_at = now
        case_row = existing
    else:
        case_row = models.AuditCase(
            user_id=current.id,
            project_id=project.id,
            case_id=generated["case_id"],
            priority_tier=generated["priority"]["tier"],
            priority_label=generated["priority"]["tier_label"],
            risk_score=generated["risk"]["risk_score"],
            risk_level=generated["risk"]["risk_level"],
            status="Open",
            created_at=now,
        )
        db.add(case_row)
    db.commit()
    db.refresh(case_row)
    return {
        "case_row_id": case_row.id,
        "case_id": case_row.case_id,
        "project_id": project.id,
        "saved": True,
        "priority_tier": case_row.priority_tier,
        "priority_label": case_row.priority_label,
    }


@router.patch("/me/audit-cases/{project_id}")
def update_case_status(
    project_id: int,
    payload: CaseStatusUpdate,
    current: models.User = Depends(auth.require_role("auditor")),
    db: Session = Depends(get_db),
):
    if payload.status not in USER_STATUSES:
        raise HTTPException(status_code=400, detail=f"status must be one of {USER_STATUSES}")
    case = (
        db.query(models.AuditCase)
        .filter(models.AuditCase.user_id == current.id, models.AuditCase.project_id == project_id)
        .first()
    )
    if not case:
        raise HTTPException(status_code=404, detail="No saved case found for this project")
    case.status = payload.status
    # Keep the linked investigation status in step when present.
    inv = (
        db.query(models.UserInvestigation)
        .filter(models.UserInvestigation.user_id == current.id, models.UserInvestigation.project_id == project_id)
        .first()
    )
    if inv:
        inv.status = payload.status
        inv.updated_at = _now_iso()
    db.commit()
    return {"case_id": case.case_id, "case_status": case.status}


# ═══════════════ System-wide view (admin) ═══════════════

@router.get("/admin/investigations", dependencies=[Depends(auth.require_role("admin"))])
def all_investigations(
    limit: int = 500,
    db: Session = Depends(get_db),
):
    rows = (
        db.query(models.UserInvestigation, models.Project, models.User)
        .join(models.Project, models.Project.id == models.UserInvestigation.project_id)
        .outerjoin(models.User, models.User.id == models.UserInvestigation.user_id)
        .order_by(models.UserInvestigation.updated_at.desc())
        .limit(limit)
        .all()
    )
    items = [{
        "investigation_id": inv.id,
        "user_name": (user.name if user else "Unknown"),
        "user_email": (user.email if user else "Unknown"),
        "project_id": project.id,
        "project_name": project.project_name,
        "investigation_status": inv.status,
        "priority_tier": inv.priority_tier,
        "risk_score_at_start": inv.risk_score_at_start,
        "updated_at": inv.updated_at,
    } for inv, project, user in rows]
    return {"items": items, "total": len(items)}


# ═══════════════ District Authority (lateral role) ═══════════════

@router.get("/me/district/projects")
def district_projects(
    limit: int = 200,
    current: models.User = Depends(auth.require_capability("inquiry:respond")),
    db: Session = Depends(get_db),
):
    """Projects for the authority's assigned district. Falls back to the
    assigned state when no district is set; returns nothing meaningful when
    neither is assigned (admin must set an assignment first)."""
    if current.assigned_district:
        filt = models.Project.district == current.assigned_district
    elif current.assigned_state:
        filt = models.Project.state == current.assigned_state
    else:
        return {"items": [], "total": 0, "scope": None,
                "message": "No district/state assignment yet — contact an administrator"}
    scope = current.assigned_district or current.assigned_state
    rows = (
        db.query(models.Project, models.RiskScore)
        .outerjoin(models.RiskScore, models.RiskScore.project_id == models.Project.id)
        .filter(filt)
        .order_by(models.RiskScore.risk_score.desc().nullslast())
        .limit(max(1, min(limit, 500)))
        .all()
    )
    # Linked payment-ledger spend for the page (authoritative per-project
    # expenditure; the catalog column is a zeroed legacy stamp).
    _rec_rows = {
        r.project_id: float(r.linked_expenditure or 0.0)
        for r in db.query(models.ProjectRecInfo)
        .filter(models.ProjectRecInfo.project_id.in_([p.id for p, _ in rows]))
        .all()
    } if rows else {}
    items = [{
        "project_id": p.id,
        "project_name": p.project_name,
        "state": p.state,
        "district": p.district,
        "constituency": p.constituency,
        "status": p.status,
        "sanctioned_amount": p.sanctioned_amount,
        "expenditure": _rec_rows.get(p.id, 0.0),
        "completion_percentage": p.completion_percentage,
        "risk_score": (r.risk_score if r else None),
        "risk_level": (r.risk_level if r else None),
    } for p, r in rows]
    return {"items": items, "total": len(items), "scope": scope}


@router.get("/me/inquiries")
def my_inquiries(
    current: models.User = Depends(auth.require_capability("inquiry:respond")),
    db: Session = Depends(get_db),
):
    """Open + recently-responded inquiries routed to this authority's district."""
    q = db.query(models.Inquiry, models.Project)
    if current.assigned_district:
        q = q.filter(models.Inquiry.district == current.assigned_district)
    elif current.assigned_state:
        q = q.join(models.Project, models.Project.id == models.Inquiry.project_id).filter(
            models.Project.state == current.assigned_state
        )
    else:
        return {"items": [], "total": 0, "scope": None}
    rows = q.order_by(models.Inquiry.created_at.desc()).limit(200).all()
    items = [{
        "inquiry_id": i.id,
        "project_id": p.id if p else i.project_id,
        "project_name": (p.project_name if p else None),
        "district": i.district,
        "question": i.question,
        "status": i.status,
        "response_text": i.response_text,
        "responded_by_name": i.responded_by_name,
        "responded_at": i.responded_at,
        "issued_by_name": i.issued_by_name,
        "created_at": i.created_at,
    } for i, p in rows]
    return {"items": items, "total": len(items), "scope": current.assigned_district or current.assigned_state}


@router.get("/me/district/summary")
def district_summary(
    current: models.User = Depends(auth.require_capability("inquiry:respond")),
    db: Session = Depends(get_db),
):
    """Small aggregate dashboard for the assigned district (SQL-side)."""
    from sqlalchemy import func
    if not (current.assigned_district or current.assigned_state):
        return {"scope": None, "projects": 0, "open_inquiries": 0,
                "high_risk": 0, "total_sanctioned": 0, "total_expenditure": 0}
    filt = (
        models.Project.district == current.assigned_district
        if current.assigned_district
        else models.Project.state == current.assigned_state
    )
    scope = current.assigned_district or current.assigned_state
    proj = db.query(
        func.count(models.Project.id).label("n"),
        func.coalesce(func.sum(models.Project.sanctioned_amount), 0.0).label("sanc"),
    ).filter(filt).one()
    # Authoritative expenditure: payment ledger scoped by the ledger's own
    # state column (labels match the catalog 1:1). District-scoped ledger
    # totals are unavailable — the ledger's IDA strings don't match the
    # catalog's district values in this dataset.
    import metrics as _metrics
    led = (
        _metrics.ledger_totals_scoped(db, state=current.assigned_state)
        if current.assigned_state
        else _metrics.ledger_totals(db)
    )
    filt_risk = filt
    high_risk = (
        db.query(func.count(models.Project.id))
        .join(models.RiskScore, models.RiskScore.project_id == models.Project.id)
        .filter(filt_risk, models.RiskScore.risk_score >= 75)
        .scalar()
    ) or 0
    if current.assigned_district:
        open_inq = (
            db.query(func.count(models.Inquiry.id))
            .filter(models.Inquiry.district == current.assigned_district,
                    models.Inquiry.status == "open")
            .scalar()
        ) or 0
    else:
        open_inq = (
            db.query(func.count(models.Inquiry.id))
            .join(models.Project, models.Project.id == models.Inquiry.project_id)
            .filter(models.Project.state == current.assigned_state,
                    models.Inquiry.status == "open")
            .scalar()
        ) or 0
    return {
        "scope": scope,
        "projects": proj.n,
        "total_sanctioned": float(proj.sanc or 0),
        "total_expenditure": float(led["total_expenditure"]),
        "high_risk": high_risk,
        "open_inquiries": open_inq,
        "expenditure_scope": "state" if current.assigned_state else "full_ledger",
    }
